### ISSUE TITLE
Python client crashes on bad client info

### ISSUE THREAD

**Issue by arjunravinarayan** [dubey/weaver#1]
Following the tutorial, If I give a command to start a Weaver client that has a bad IP, or port, Weaver crashes with:

```
 c = client.Client('127.0.0.1', 2001)
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0408 19:14:19.257675  5041 server_manager_link.cc:138] could not get replicant               id
python: client/client.cc:45: cl::client::client(const char*, uint16_t, const cha              r*): Assertion `m_sm.get_replid(myid) && "get repl_id"' failed.
^[[AAborted (core dumped)
```

Note that the port here is wrong, the tutorial sets it up at port 2002. However, rather than crashing, it should probably fail gracefully instead.

**Comment by dubey** [comment]
Fixed in 09cf4222b366dd63f08467fdd631dee18d904ac9.
